// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Watchlist.API.Context;

namespace Watchlist.API.Migrations
{
    [DbContext(typeof(WatchlistContext))]
    partial class WatchlistContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Watchlist.API.Entities.Watchlist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<Guid>("Userid");

                    b.HasKey("Id");

                    b.ToTable("WatchLists");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c3e95c44-1e39-4328-9d52-e0291ddf2da7"),
                            Name = "WatchlaterPlaylist",
                            Userid = new Guid("434c538e-7aed-42d7-a667-92b0760ef88c")
                        },
                        new
                        {
                            Id = new Guid("34487500-ba60-4962-9342-907c4665681f"),
                            Name = "WatchlaterPlaylist",
                            Userid = new Guid("36de8e2f-e3ff-4718-a2e8-c9fc08610728")
                        },
                        new
                        {
                            Id = new Guid("1c389e4c-0272-48ea-b260-6b29c0c51ad7"),
                            Name = "WatchlaterPlaylist",
                            Userid = new Guid("443ed08c-e98a-4ac1-84ed-fee7b27513f9")
                        });
                });

            modelBuilder.Entity("Watchlist.API.Entities.WatchlistMedia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("MediaId");

                    b.Property<Guid>("WatchlistId");

                    b.HasKey("Id");

                    b.HasIndex("WatchlistId");

                    b.ToTable("WatchListsMedias");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e0545da1-bc9c-47b6-aa2c-b81e61424a30"),
                            MediaId = new Guid("4259cac2-fcf2-4ca2-b311-813bc291c2ce"),
                            WatchlistId = new Guid("c3e95c44-1e39-4328-9d52-e0291ddf2da7")
                        },
                        new
                        {
                            Id = new Guid("b25a6a4c-eefe-4793-aa5d-5b2d357f4d29"),
                            MediaId = new Guid("b79a54f9-45a2-421b-735e-08d713cec375"),
                            WatchlistId = new Guid("c3e95c44-1e39-4328-9d52-e0291ddf2da7")
                        },
                        new
                        {
                            Id = new Guid("0c58c6e8-2c84-4b7a-b6a5-068652b0058a"),
                            MediaId = new Guid("8d81a6f1-f933-429a-91fb-7d38cd54b142"),
                            WatchlistId = new Guid("c3e95c44-1e39-4328-9d52-e0291ddf2da7")
                        });
                });

            modelBuilder.Entity("Watchlist.API.Entities.WatchlistMedia", b =>
                {
                    b.HasOne("Watchlist.API.Entities.Watchlist", "WatchList")
                        .WithMany("Medias")
                        .HasForeignKey("WatchlistId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
